from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel
from app.db.database import get_db
from app.db.models import Document, ChatHistory, User
from app.api.endpoints.auth import get_current_user
from app.services.chroma_service import ChromaService
from app.services.ai_service import AIService
import datetime

router = APIRouter(prefix="/chat", tags=["chat"])

# Input Schema
class ChatQueryRequest(BaseModel):
    document_id: str
    question: str

# Output Citations Schema (exactly as requested: page and text)
class SourceCitation(BaseModel):
    page: int
    text: str

class ChatResponse(BaseModel):
    id: int
    question: str
    answer: str
    sources: List[SourceCitation]
    created_at: datetime.datetime

class ChatHistoryResponse(BaseModel):
    id: int
    question: str
    answer: str
    sources: List[SourceCitation]
    created_at: datetime.datetime

    class Config:
        from_attributes = True


@router.post("/query", response_model=ChatResponse, status_code=status.HTTP_200_OK)
def query_document(
    request: ChatQueryRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Query a contract. Performs semantic vector query and generates referenced answers."""
    # 1. Authorize document access
    doc = db.query(Document).filter(Document.id == request.document_id, Document.user_id == current_user.id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found or access denied")
    
    if doc.status != "completed":
        raise HTTPException(
            status_code=400, 
            detail=f"Document is currently in status '{doc.status}' and cannot be queried yet."
        )

    # 2. Retrieve history for conversation context (last 6 messages)
    history_records = db.query(ChatHistory).filter(
        ChatHistory.document_id == request.document_id,
        ChatHistory.user_id == current_user.id
    ).order_by(ChatHistory.created_at.asc()).all()

    chat_history_list = [
        {"question": record.question, "answer": record.answer}
        for record in history_records[-6:]
    ]

    # 3. Retrieve relevant context from vector index (Top K = 5 as requested in Phase 4!)
    retrieved_chunks = ChromaService.query_document(request.document_id, request.question, limit=5)
    if not retrieved_chunks:
        retrieved_chunks = [{"text": "No specific context available on this topic.", "page_number": 1}]

    # 4. Invoke LLM (checks OpenAI -> Gemini -> Mock Fallback)
    ai_response = AIService.query_chat(request.question, retrieved_chunks, chat_history_list)

    answer = ai_response.get("answer", "I could not formulate an answer for this question.")
    sources_raw = ai_response.get("sources", [])

    # Format sources exactly as page/text response structure
    formatted_sources = []
    for s in sources_raw:
        # Standardize keys (might be page/page_number, text/excerpt depending on model outputs)
        page_val = s.get("page", s.get("page_number", 1))
        text_val = s.get("text", s.get("excerpt", ""))
        formatted_sources.append({
            "page": int(page_val),
            "text": str(text_val)
        })

    # If no citations were generated by AI but we have chunks retrieved, attach top 2 retrieved chunks
    if not formatted_sources and retrieved_chunks:
        for chunk in retrieved_chunks[:2]:
            formatted_sources.append({
                "page": chunk.get("page_number", 1),
                "text": chunk.get("text", "")[:200]
            })

    # 5. Save session details to Database
    db_chat = ChatHistory(
        user_id=current_user.id,
        document_id=request.document_id,
        question=request.question,
        answer=answer,
        sources=formatted_sources
    )
    db.add(db_chat)
    db.commit()
    db.refresh(db_chat)

    return db_chat


@router.get("/history/{document_id}", response_model=List[ChatHistoryResponse])
def get_chat_history(
    document_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieve chat history log list for a specific contract."""
    doc = db.query(Document).filter(Document.id == document_id, Document.user_id == current_user.id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found or access denied")

    history = db.query(ChatHistory).filter(
        ChatHistory.document_id == document_id,
        ChatHistory.user_id == current_user.id
    ).order_by(ChatHistory.created_at.asc()).all()
    
    return history
